version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/app/models
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 6G

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    depends_on:
      - ollama
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OLLAMA_API=http://ollama:11434/api/generate
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  ollama_data: 